project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"

website:
  title: "Yanyu Li"
  description: "Speech perception | Prosody | Experimental methods"
  navbar:
    background: light
    left:
      - text: "Welcome"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
  page-footer:
    left: "Copyright 2026, Yanyu Li"
    right:
      - text: "GitHub"
        href: "https://github.com/yanyuulii"
      - text: "Google Scholar"
        href: "https://scholar.google.com/citations?user=gXpRx9UAAAAJ&hl=en"

format:
  html:
    theme: 
      light: Flatly
      dark:  Darkly
    toc: true
    toc-location: left
    highlight-style: 
      light: a11y-light
      dark: a11y-dark


