# Journal articles

- Coretta, S., Casillas, J. V., …, [Li, Y]{.underline}, ... & Wood, A. (2023). Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human-speech analyses. *Advances in Methods and Practices in Psychological Science*, 6(3). 
[doi](https://doi.org/10.1177/25152459231162567) [pdf](assets/paper/many_speech.pdf)

- Chen, S., [Li, Y.]{.underline}, Arche, M.J., Monks, C.P., & White L. (third-round revision, Studies in Second Language Acquisition). *Teaching Mandarin tones to English speakers via intonational analogy*.

- [Li, Y.]{.underline}, Hoogland, D., Duncan, D., & Zhang, C. (first-round revision, *Linguistic Vanguard*). Gamification in Phonetic Data Collection: Accent Recognition of Northeast England Regions.

- [Li, Y.]{.underline}, White, L., & Khattab, G. (submitted to Bilingualism: *Language and Cognition*). The Effect of Incremental Cue Training in Phonetic Learning of Lexical Tones.

- [Li, Y.]{.underline}, White, L., & Khattab, G. (in preparation). The Effect of Incrementally Reducing Cue Exaggeration: an Extended Training in Phonetic Learning of Lexical Tones.


# Conference proceedings

- Li, Y., White, L., & Khattab, G. (2023). Incremental cue training: a study of lexical tone learning by non-tonal listeners. *In Proceedings of the 20th International Congress of Phonetic Sciences–ICPhS 2023*.
[pdf](assets/paper/icphs_paper.pdf)

