# Course

I am currently covering the lectures on Advanced Statistics for the module Research Methods in Practice III - SPE3056 for Speech and Language Sciences Stage 3 students. 

# Past teaching
During my PhD, I have been mainly leading undergraduate/postgraduate seminars on courses related to phonetics and phonology, and leading workshops on statistics and quantitative analysis at Newcastle University. 

## Experimental methods related

Key modules include:

- Quantitative Methods (Data Analysis in R)
- Phonetics I and II
- Language variation & change: dealing with data.

where I mainly 
1) developed lab materials and led tutorials using relevant tools including R and Praat. Specifically, I developed lab materials and ran statistical workshops for the module Quantitative Methods, which introduced students to various levels of data analysis including R coding, data wrangling and visualisation, and linear-regression based inferential statistic tests. 
2) In the module Phonetics I and II, I led Praat tutorials demonstrating students to read and extract segmental and suprasegmentaion acoustic information based on speech recordings. 
3) In the module Language Variation and Change: Dealing with Data, I trained students to visualise and report linguistic data for distributional analysis. 
4) I also marked assignments at the end of each term. 


## Phonetics & phonology related

Key modules include:

- Phonetics I and II (school of ECLS)
- Phonetics & Phonology (school of SELLL)

where I mainly provided phonetic ear training of the IPA chart, marked assignments, and arranged one-to-one student consultation hours.

## Language school

I also worked as a lecturer and course designer at a language school called Guixue in Zhengzhou, China, where I developed course content and led 4 modules for studying to prepare for IELTS. Improved students’ scores on average from 4.5 – 6.



